/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author informatica1
 */
public class fasfasf extends javax.swing.JPanel {

    /**
     * Creates new form frmDashboard
     */
    public fasfasf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel2 = new custom.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAdminDashboard = new javax.swing.JLabel();
        panelRedondeado21 = new custom.PanelRedondeado2();
        txtCredenciales2 = new javax.swing.JLabel();
        txtNombreDashboard = new javax.swing.JLabel();
        txtEmailDashboard = new javax.swing.JLabel();
        panelRedondeado22 = new custom.PanelRedondeado2();
        txtCredenciales1 = new javax.swing.JLabel();
        txtEdadDashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPaisDashboard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCiudadDashboard = new javax.swing.JLabel();
        txtUsuarioDashboard = new javax.swing.JLabel();
        roundPanel4 = new custom.RoundPanel();
        txtUsuarioDashboard1 = new javax.swing.JLabel();
        txtUsuarioDashboard4 = new javax.swing.JLabel();
        roundPanel5 = new custom.RoundPanel();
        txtUsuarioDashboard5 = new javax.swing.JLabel();
        txtUsuarioDashboard6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        roundPanel2.setBackground(new java.awt.Color(252, 252, 252));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/sddefault.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        roundPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 70, 80);

        txtAdminDashboard.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAdminDashboard.setForeground(new java.awt.Color(102, 102, 102));
        txtAdminDashboard.setText("Email");
        roundPanel2.add(txtAdminDashboard);
        txtAdminDashboard.setBounds(120, 60, 100, 30);

        panelRedondeado21.setBackground(new java.awt.Color(255, 255, 255));

        txtCredenciales2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtCredenciales2.setText("Credenciales");

        txtNombreDashboard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNombreDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreDashboard.setText("Nombre");

        txtEmailDashboard.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        txtEmailDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailDashboard.setText("Email");

        javax.swing.GroupLayout panelRedondeado21Layout = new javax.swing.GroupLayout(panelRedondeado21);
        panelRedondeado21.setLayout(panelRedondeado21Layout);
        panelRedondeado21Layout.setHorizontalGroup(
            panelRedondeado21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCredenciales2))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelRedondeado21Layout.setVerticalGroup(
            panelRedondeado21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCredenciales2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmailDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        roundPanel2.add(panelRedondeado21);
        panelRedondeado21.setBounds(30, 130, 460, 120);

        panelRedondeado22.setBackground(new java.awt.Color(255, 255, 255));

        txtCredenciales1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtCredenciales1.setText("Sobre mí ");

        txtEdadDashboard.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        txtEdadDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtEdadDashboard.setText("Edad");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Edad:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("País");

        txtPaisDashboard.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        txtPaisDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtPaisDashboard.setText("Edad");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad:");

        txtCiudadDashboard.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        txtCiudadDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtCiudadDashboard.setText("Edad");

        javax.swing.GroupLayout panelRedondeado22Layout = new javax.swing.GroupLayout(panelRedondeado22);
        panelRedondeado22.setLayout(panelRedondeado22Layout);
        panelRedondeado22Layout.setHorizontalGroup(
            panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCredenciales1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRedondeado22Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdadDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRedondeado22Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaisDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRedondeado22Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCiudadDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelRedondeado22Layout.setVerticalGroup(
            panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCredenciales1)
                .addGap(18, 18, 18)
                .addGroup(panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPaisDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelRedondeado22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCiudadDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        roundPanel2.add(panelRedondeado22);
        panelRedondeado22.setBounds(30, 290, 460, 200);

        txtUsuarioDashboard.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtUsuarioDashboard.setText("Usuario");
        roundPanel2.add(txtUsuarioDashboard);
        txtUsuarioDashboard.setBounds(120, 40, 100, 30);

        roundPanel4.setBackground(new java.awt.Color(204, 204, 255));

        txtUsuarioDashboard1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtUsuarioDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioDashboard1.setText("Empleadores");
        roundPanel4.add(txtUsuarioDashboard1);
        txtUsuarioDashboard1.setBounds(30, 30, 140, 30);

        txtUsuarioDashboard4.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtUsuarioDashboard4.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioDashboard4.setText("999");
        roundPanel4.add(txtUsuarioDashboard4);
        txtUsuarioDashboard4.setBounds(290, 70, 150, 40);

        roundPanel5.setBackground(new java.awt.Color(204, 204, 204));

        txtUsuarioDashboard5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtUsuarioDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioDashboard5.setText("Solicitantes");
        roundPanel5.add(txtUsuarioDashboard5);
        txtUsuarioDashboard5.setBounds(30, 30, 140, 30);

        txtUsuarioDashboard6.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtUsuarioDashboard6.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioDashboard6.setText("999");
        roundPanel5.add(txtUsuarioDashboard6);
        txtUsuarioDashboard6.setBounds(300, 60, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(roundPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private custom.PanelRedondeado2 panelRedondeado21;
    private custom.PanelRedondeado2 panelRedondeado22;
    private custom.RoundPanel roundPanel2;
    private custom.RoundPanel roundPanel4;
    private custom.RoundPanel roundPanel5;
    public javax.swing.JLabel txtAdminDashboard;
    public javax.swing.JLabel txtCiudadDashboard;
    private javax.swing.JLabel txtCredenciales1;
    private javax.swing.JLabel txtCredenciales2;
    public javax.swing.JLabel txtEdadDashboard;
    public javax.swing.JLabel txtEmailDashboard;
    public javax.swing.JLabel txtNombreDashboard;
    public javax.swing.JLabel txtPaisDashboard;
    public javax.swing.JLabel txtUsuarioDashboard;
    public javax.swing.JLabel txtUsuarioDashboard1;
    public javax.swing.JLabel txtUsuarioDashboard4;
    public javax.swing.JLabel txtUsuarioDashboard5;
    public javax.swing.JLabel txtUsuarioDashboard6;
    // End of variables declaration//GEN-END:variables
}
