/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ctrlCambiarContrasena;
import controlador.ctrlIngresoCorreo;
import java.awt.Color;
import modelo.UsuarioEscritorio;
import static vista.frmIngresoCorreo.initFrmIngresoCorreo;

/**
 *
 * @author Jero
 */
public class frmCambiarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form frmCambiarContrasena
     */
    public frmCambiarContrasena() {
        initComponents();
    }
    
     public static void initFrmCambiarContrasena(){
        UsuarioEscritorio modelo = new UsuarioEscritorio();
         frmCambiarContrasena vista = new frmCambiarContrasena();
        ctrlCambiarContrasena controlador = new ctrlCambiarContrasena(modelo, vista);
        
        vista.setVisible(true);
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiarContrasena = new javax.swing.JButton();
        txtConfirmarContrasena = new javax.swing.JTextField();
        txtNuevaContrasena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnCambiarContrasena.setBackground(new java.awt.Color(0, 0, 0));
        btnCambiarContrasena.setText("Cambiar Contraseña");

        txtConfirmarContrasena.setText("Repetir Contraseña");
        txtConfirmarContrasena.setToolTipText("");
        txtConfirmarContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmarContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmarContrasenaFocusLost(evt);
            }
        });

        txtNuevaContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtNuevaContrasena.setText("Escriba Su Nueva Contraseña");
        txtNuevaContrasena.setToolTipText("");
        txtNuevaContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNuevaContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevaContrasenaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(txtConfirmarContrasena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCambiarContrasena)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevaContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevaContrasenaFocusGained
        if (txtNuevaContrasena.getText().equals("Escriba Su Nueva Contraseña")) {
         txtNuevaContrasena.setText("");
         txtNuevaContrasena.setForeground(new Color(153,153,153));
     }
    }//GEN-LAST:event_txtNuevaContrasenaFocusGained

    private void txtConfirmarContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarContrasenaFocusLost
        if (txtConfirmarContrasena.getText().equals("")) {
         txtConfirmarContrasena.setText("Repetir Contraseña");
         txtConfirmarContrasena.setForeground(new Color(153,153,153));
           }
    }//GEN-LAST:event_txtConfirmarContrasenaFocusLost

    private void txtConfirmarContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarContrasenaFocusGained
          if (txtConfirmarContrasena.getText().equals("Repetir Contraseña")) {
         txtConfirmarContrasena.setText("");
         txtConfirmarContrasena.setForeground(new Color(153,153,153));
           }
    }//GEN-LAST:event_txtConfirmarContrasenaFocusGained

    private void txtNuevaContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevaContrasenaFocusLost
         if (txtNuevaContrasena.getText().equals("")) {
         txtNuevaContrasena.setText("Escriba Su Nueva Contraseña");
         txtNuevaContrasena.setForeground(new Color(153,153,153));
           }
    }//GEN-LAST:event_txtNuevaContrasenaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initFrmCambiarContrasena();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarContrasena;
    public javax.swing.JTextField txtConfirmarContrasena;
    public javax.swing.JTextField txtNuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
