/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author informatica1
 */
public class frmDashboard extends javax.swing.JPanel {

    /**
     * Creates new form frmDashboard
     */
    public frmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel2 = new custom.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailDashboard = new javax.swing.JLabel();
        txtEmailDashboard1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/sddefault.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        roundPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 70, 80);

        txtEmailDashboard.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtEmailDashboard.setForeground(new java.awt.Color(153, 153, 153));
        txtEmailDashboard.setText("Email");
        roundPanel2.add(txtEmailDashboard);
        txtEmailDashboard.setBounds(120, 60, 100, 30);

        txtEmailDashboard1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtEmailDashboard1.setText("Email");
        roundPanel2.add(txtEmailDashboard1);
        txtEmailDashboard1.setBounds(120, 30, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private custom.RoundPanel roundPanel2;
    public javax.swing.JLabel txtEmailDashboard;
    public javax.swing.JLabel txtEmailDashboard1;
    // End of variables declaration//GEN-END:variables
}
