/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ctrlMenu;
import modelo.UsuarioEscritorio;

/**
 *
 * @author Gudelia
 */
public class frmMenu extends javax.swing.JFrame {

   public static void initfrmMenu(UsuarioEscritorio modelo) {
        frmMenu vista = new frmMenu();
        frmDashboard frmDashboard = new frmDashboard();
        frmAdministrarUsuarios frmAdministrarUsuarios = new frmAdministrarUsuarios();
        frmEmpresa frmEmpresa = new frmEmpresa();
        frmSolicitantes frmSolicitantes = new frmSolicitantes();
        frmTrabajos frmTrabajos = new frmTrabajos();

        ctrlMenu controlador = new ctrlMenu(vista, frmDashboard, frmAdministrarUsuarios, frmEmpresa, frmSolicitantes, frmTrabajos, modelo);

        vista.setVisible(true);
    }

    /**
     * Creates new form menu
     */
    public frmMenu() {
        initComponents();
    }
    
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTrabajos = new custom.Button();
        btnHome = new custom.Button();
        btnAdd = new custom.Button();
        btnEmpresa = new custom.Button();
        btnsolicitantes = new custom.Button();
        jPContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 29, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Herramientas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Personalizar");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnTrabajos.setBackground(new java.awt.Color(0, 29, 63));
        btnTrabajos.setForeground(new java.awt.Color(255, 255, 255));
        btnTrabajos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrabajos.setShadowColor(new java.awt.Color(0, 29, 63));
        jPanel2.add(btnTrabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 230, 60));

        btnHome.setBackground(new java.awt.Color(0, 29, 63));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/dashboard.png"))); // NOI18N
        btnHome.setText("Dashboard");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setShadowColor(new java.awt.Color(0, 29, 63));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 60));

        btnAdd.setBackground(new java.awt.Color(0, 29, 63));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/config.png"))); // NOI18N
        btnAdd.setText("Administrador");
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.setShadowColor(new java.awt.Color(0, 29, 63));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        btnEmpresa.setBackground(new java.awt.Color(0, 29, 63));
        btnEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/empresa.png"))); // NOI18N
        btnEmpresa.setText("Empresa");
        btnEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpresa.setShadowColor(new java.awt.Color(0, 29, 63));
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 60));

        btnsolicitantes.setBackground(new java.awt.Color(0, 29, 63));
        btnsolicitantes.setForeground(new java.awt.Color(255, 255, 255));
        btnsolicitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/Diseño sin título (3).png"))); // NOI18N
        btnsolicitantes.setText("Solicitante");
        btnsolicitantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsolicitantes.setShadowColor(new java.awt.Color(0, 29, 63));
        jPanel2.add(btnsolicitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 800));

        jPContenedor.setBackground(new java.awt.Color(242, 241, 241));
        jPContenedor.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1270, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
     
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
  
    }//GEN-LAST:event_btnEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
            UsuarioEscritorio modelo = new UsuarioEscritorio(); // Crea un objeto UsuarioEscritorio
            initfrmMenu(modelo); // Pasa el objeto al método initfrmMenu
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public custom.Button btnAdd;
    public custom.Button btnEmpresa;
    public custom.Button btnHome;
    public custom.Button btnTrabajos;
    public custom.Button btnsolicitantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPContenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
