/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Estudiante
 */
public class gestionarAdministradores extends javax.swing.JPanel {

    /**
     * Creates new form configuraciones
     */
    public gestionarAdministradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioAdmin = new custom.TextField();
        txtNombreAdmin = new custom.TextField();
        txtCorreoAdmin = new custom.TextField();
        txtContrasenaAdmin = new custom.PasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAdministradores = new javax.swing.JTable();
        btnEliminarAdmin = new custom.Button();
        btnAgregarAdmin = new custom.Button();
        btnEditarAdmin = new custom.Button();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Añadir Administradores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtUsuarioAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuarioAdmin.setText("Usuario");
        add(txtUsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 460, 60));

        txtNombreAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreAdmin.setText("Nombre");
        add(txtNombreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 460, 60));

        txtCorreoAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoAdmin.setText("Correo Electrónico");
        add(txtCorreoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 460, 60));

        txtContrasenaAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasenaAdmin.setText("Contraseña");
        add(txtContrasenaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 460, 60));

        jtbAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbAdministradores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 500, 470));

        btnEliminarAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAdmin.setText("Eliminar Administrador");
        add(btnEliminarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 170, 50));

        btnAgregarAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarAdmin.setText("Agregar administrador");
        add(btnAgregarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 170, 50));

        btnEditarAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAdmin.setText("Editar Administrador");
        add(btnEditarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 170, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public custom.Button btnAgregarAdmin;
    public custom.Button btnEditarAdmin;
    public custom.Button btnEliminarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtbAdministradores;
    public custom.PasswordField txtContrasenaAdmin;
    public custom.TextField txtCorreoAdmin;
    public custom.TextField txtNombreAdmin;
    public custom.TextField txtUsuarioAdmin;
    // End of variables declaration//GEN-END:variables
}
